### ISSUE TITLE
Request path transformation 😱

### ISSUE THREAD

**Issue by vassilevsky** [Rohde-Schwarz/sparrow#19]
Our sweet frontenders threw in this neat idea. They want to use camel case URLs:

```
GET /api/v1/emailSubscribers
```

We would very much want to never see such URLs and would much welcome their transformation to snake case ones like we Rails people understand:

```
GET /api/v1/email_subscribers
```

Is this even possible with this gem?

No response transformation is needed in this case.

**Comment by enricogenauck** [comment]
I was just thinking about this feature and two points came up which might be worth discussing:

**Routes**
I am wondering, wether this might break tools like `rake routes`? This feature could potentially introduce a large number of new routes variations which would be hidden from `rake routes` and could increase debugging time.

**Limitation of scope**
The usage of sparrow introduces a certain level of ambiguity of an API's behaviour by accepting different key notations. But this effect is limited to the request's json body which creates a clear scope and limits its effect for potential bug hunt or surprising effects for developers.

When this ambiguity is extended to the URI level, we would open up the problem space immensly. Since sparrow tries to handle requests and responses as well, we will have to solve questions like:

* Do we manipulate the referrer property of the request?
* Do we manipulate the location of a redirect response?
* What about URIs in the json response content? Links to the next page on paginated resource lists or other elements one would find in implementations like [JSON API](http://jsonapi.org)?

I think, we should discuss this feature and its feasibility and implications further. I'm looking forward to your thoughts and ideas.


Enrico
